#! /bin/sh

# configure desktops on multi monitors
bspc monitor eDP -d I II III
bspc monitor DisplayPort-0 -d IV V VI
bspc monitor HDMI-A-0 -d VII VIII IX

bspc config border_width        2
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off

# launch sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# launch compositor
picom -b

# set wallpaper
feh --no-fehbg --bg-fill /usr/share/pixmaps/wallpaper

# launch polybar
$HOME/.config/polybar/launch.sh

# launch fcitx5
fcitx5 &

# launch nm-applet for wireless connection
$HOME/WW/Misc/nmgui/nmgui connect
