#!/bin/sh

# assign all ten monitors to eDP (laptop's screen)
bspc monitor eDP -d I II III IV V VI VII VIII IX X
# auto config monitors
autorandr -c

bspc config border_width        2
bspc config window_gap          8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off

# launch sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# launch compositor
picom -b

# set wallpaper
feh --no-fehbg --bg-fill /usr/share/pixmaps/wallpaper

# launch dunst
/usr/bin/dunst &

# launch polybar
$HOME/.config/polybar/launch.sh

# XDG autostart
systemctl --user start autostart.target

# wireless auto-connection
$HOME/WW/Misc/nmgui/nmgui connect
