#!/bin/bash

for commit in $(cat /tmp/leo.commit); do
  if ! git cherry-pick ${commit}; then
    read -p "Press key to continue.. " -n1 -s;
  fi 
  if [[ -d note || -e update.md ]]; then
    read -p "Press key to continue.. " -n1 -s;
  fi 
done
