#!/bin/sh

_http_proxy=127.0.0.1
_http_proxy_port=7891

_socks_proxy=127.0.0.1
_socks_proxy_port=7890

#socat - PROXY:$_http_proxy:$1:$2,proxyport=$_http_proxy_port
socat - SOCKS4A:$_socks_proxy:$1:$2,socksport=$_socks_proxy_port
