#!/bin/bash

checkProcess(){
    if [[ $# -gt 0 ]]; then
        echo "$(ps ux | tail -n +2 | awk '{print $11}' | grep "$1")"
    fi
}

checkConnect(){
    if [[ $# -gt 0 ]]; then
        echo "$(nmcli d show $1 | grep "GENERAL.STATE" | grep "100 (connected)")"
    fi
}

waitUntil(){
    if [[ $# -gt 2 ]]; then
        sleepTime=$3
    else
        sleepTime=5
    fi

    while true; do
        case $1 in
            "start")
                if [[ -n "$(checkProcess "$2")" ]]; then
                    #echo "program started"
                    break
                fi
            ;;
            "stop")
                if [[ -z "$(checkProcess "$2")" ]]; then
                    #echo "program stopped"
                    break
                fi
            ;;
        esac

        sleep $sleepTime
    done
}

connect(){
    if [[ $2 == "autoexit" && -n "$(checkConnect $1)" ]]; then
        return
    fi

    if [[ -z "$(checkProcess nm-applet)" ]]; then
        nm-applet 2>&1 > /dev/null &
    fi

    waitUntil start nm-applet
    sleep 5

    if [[ "$2" = "autoexit" ]]; then
        nmcli device connect $1 2>&1 > /dev/null
        sleep 10
    fi

    while true; do
        if [[ -n "$(checkConnect $1)" ]]; then
            break
        fi
        sleep 60
    done

    if [[ "$2" = "autoexit" ]]; then
        killNMApplet
    fi
}

edit(){
    nm-applet 2>&1 > /dev/null &
    nm-connection-editor 2>&1 > /dev/null &

    waitUntil stop nm-connection-editor 60

    killNMApplet
}

killNMApplet(){
    killall nm-applet
}

case $1 in
    "connect") connect wlp3s0 autoexit &
	;;
    "edit") edit &
	;;
    "kill") killNMApplet &
	;;
    "help") showHelp
	;;
    *) connect wlp3s0 &
	;;
esac
