#!/bin/python3

import os

def sysPkg():
    curDir = os.getcwd()

    if not os.path.exists(f"{curDir}/pkg.list"):
        rst = input("File \"pkg.list\" does not exist in current folder, proceed? [y/N]")
        if not (rst == "y" or rst == "Y"):
            return

    with open(f"{curDir}/pkg.list", "w") as f:
        for pkg in os.popen("expac --timefmt='%Y-%m-%d %T' '%l\t%w\t%n\t%v' | sort").read().split("\n"):
            if len(pkg) > 0:
                pkgList = pkg.split("\t")
                f.write(f"{pkgList[0]}\t{pkgList[2]}\n\t{pkgList[1]}\t{pkgList[3]}\n\n")

def flatpakPkg():
    curDir = os.getcwd()

    if not os.path.exists(f"{curDir}/flatpak_pkg.list"):
        rst = input("File \"flatpak_pkg.list\" does not exist in current folder, proceed? [y/N]")
        if not (rst == "y" or rst == "Y"):
            return

    os.system(f"flatpak list -a --columns=name:s,application,version,branch,origin,installation,size > {curDir}/flatpak_pkg.list")

sysPkg()
flatpakPkg()
