#!/bin/bash

mountPart(){
    sudo cryptsetup open /dev/nvme0n1p2 cryptboot
    sudo mount -o compress=zstd,subvol=/@boot /dev/mapper/cryptboot /boot
    sudo mount -o compress=zstd,subvol=/@snapshots /dev/mapper/cryptboot /.snapshots/boot
    sudo mount /dev/nvme0n1p1 /efi
}

umountPart(){
    sudo umount /boot
    sudo cryptsetup close /dev/mapper/cryptboot
    sudo umount /efi
}

verify(){
    echo "Contents of /efi:"
    ls -la /efi
    echo -e "\nContents of /boot:"
    ls -la /boot
}

case $1 in
    "mount") mountPart
	;;
    "umount") umountPart
	;;
    "verify") verify
	;;
    *) showHelp
	;;
esac
