#!/bin/bash

files=( amd-ucode.img
	    initramfs-linux.img
	    initramfs-linux-fallback.img
	    vmlinuz-linux
	    initramfs-linux-zen.img
	    initramfs-linux-zen-fallback.img
	    vmlinuz-linux-zen
	    initramfs-linux-lts.img
	    initramfs-linux-lts-fallback.img
	    vmlinuz-linux-lts)

for file in "${files[@]}"; do
    sudo chmod 600 "/boot/${file}"
done
