#!/bin/bash

# clear current tpm key slot
sudo systemd-cryptenroll /dev/nvme0n1p3 --wipe-slot=tpm2
sudo systemd-cryptenroll /dev/nvme1n1p1 --wipe-slot=tpm2

# enroll new key
sudo systemd-cryptenroll --tpm2-device=/dev/tpmrm0 --tpm2-pcrs=0,1,2,3,5,7,8,9 /dev/nvme0n1p3
sudo systemd-cryptenroll --tpm2-device=/dev/tpmrm0 --tpm2-pcrs=0,1,2,3,5,7,8,9 /dev/nvme1n1p1
