#!/bin/bash

_clear() {
  echo -n "Wipe all TPM key slots for $*?"
  _askYesOrNo
  if [[ $? -eq 1 ]]; then
    for device in "$@"; do
      # clear current tpm key slot
      sudo systemd-cryptenroll "$device" --wipe-slot=tpm2
    done
  fi
}

_enroll() {
  echo -n "Enroll current PCR value for $*?"
  _askYesOrNo
  if [[ $? -eq 1 ]]; then
    for device in "$@"; do
      # enroll new key
      sudo systemd-cryptenroll --tpm2-device=/dev/tpmrm0 --tpm2-pcrs=0,1,2,3,4,5,7,8,9 "$device"
    done
  fi
}

case $1 in
  "clear")
    shift
    _clear "$@"
    ;;
  "enroll")
    shift
    _enroll "$@"
    ;;
  *)
    showHelp
    ;;
esac
