#!/bin/bash

files=( amd-ucode.img
	    initramfs-linux.img
	    initramfs-linux-fallback.img
	    vmlinuz-linux
	    initramfs-linux-zen.img
	    initramfs-linux-zen-fallback.img
	    vmlinuz-linux-zen)

for file in ${files[@]}; do
    chmod 600 "/boot/${file}"
done
