#!/bin/bash

# assign desktops to monitors
# desktop 1-4 for primary monitor
# assign from left to right
bspc desktop I -m HDMI-A-0
bspc desktop II -m HDMI-A-0
bspc desktop III -m HDMI-A-0
bspc desktop IV -m HDMI-A-0
bspc desktop V -m DisplayPort-0
bspc desktop VI -m DisplayPort-0
bspc desktop VII -m DisplayPort-0
bspc desktop VIII -m eDP
bspc desktop IX -m eDP
bspc desktop X -m eDP
