#!/bin/bash

# temporarily create a desktop named "Desktop"
bspc monitor HDMI-A-0 -a Desktop

# assign desktops to monitors evenlly
# assign from left to right
bspc desktop I -m eDP
bspc desktop II -m eDP
bspc desktop III -m eDP
bspc desktop IV -m eDP
bspc desktop V -m eDP
bspc desktop VI -m DisplayPort-0
bspc desktop VII -m DisplayPort-0
bspc desktop VIII -m DisplayPort-0
bspc desktop IX -m DisplayPort-0
bspc desktop X -m DisplayPort-0

# delete unused monitors
bspc monitor HDMI-A-0 -r &>/dev/null
