#!/bin/bash

# temporarily create a desktop named "Desktop"
bspc monitor HDMI-A-0 -a Desktop
bspc monitor DisplayPort-0 -a Desktop

# assign all desktops to laptop screen
#bspc desktop any -m eDP
bspc desktop I -m eDP
bspc desktop II -m eDP
bspc desktop III -m eDP
bspc desktop IV -m eDP
bspc desktop V -m eDP
bspc desktop VI -m eDP
bspc desktop VII -m eDP
bspc desktop VIII -m eDP
bspc desktop IX -m eDP
bspc desktop X -m eDP

# delete unused monitors
bspc monitor HDMI-A-0 -r &>/dev/null
bspc monitor DisplayPort-0 -r &>/dev/null
